main:
	python3 collect_dates.py 
	python3 filter_urls.py 
	python3 requesting_urls.py     
	python3 time_planner.py
	python3 fetch_player_statistics.py 

test:
	pytest tests.py

clean:
	rm collect_dates_regex/*
	rm datetime_filter/*
	rm NBA_player_statistics/*
	rm requesting_urls/*
	rm filter_urls/*
